version: "{build}"

stack: node 10.16.3

environment:
  matrix:
  # For regular jobs, such as push, pr and etc.
  - job_name: Linux
    appveyor_build_worker_image: ubuntu1804
    GOARCH: amd64
  - job_name: MacOS
    appveyor_build_worker_image: macos
    GOARCH: amd64
  - job_name: Windows
    appveyor_build_worker_image: Visual Studio 2019
    GOARCH: amd64 
  # For release, by pushing tag
  - job_name: linux-amd64
    appveyor_build_worker_image: ubuntu1804
    GOARCH: amd64
  - job_name: linux-arm
    appveyor_build_worker_image: ubuntu1804
    GOARCH: arm
  - job_name: linux-arm64
    appveyor_build_worker_image: ubuntu1804
    GOARCH: arm64
  - job_name: linux-386
    appveyor_build_worker_image: ubuntu1804
    GOARCH: 386
  - job_name: darwin-amd64
    appveyor_build_worker_image: macos
    GOARCH: amd64
  - job_name: windows-amd64
    appveyor_build_worker_image: Visual Studio 2019
    GOARCH: amd64
  
for:
  - # Linux
    skip_tags: true
    matrix:
      only:
        - job_name: Linux

    install:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.42.0
      - make dep
      - sh: ci_scripts/create-ip-aliases.sh
      - make install-deps-ui
    
    before_build:
      - make check
      - make lint-ui
   
    build_script:
      - make build
      - make build-ui

  - # Windows and MacOS
    skip_tags: true
    matrix:
      only:
        - job_name: MacOS
        - job_name: Windows

    environment:
      matrix:
        - GOARCH: amd64

    install:
      - sh: curl -OL "https://golang.org/dl/go1.16.6.darwin-amd64.tar.gz" && sudo tar -C /usr/local -xzf go1.16.6.darwin-amd64.tar.gz && export GOPATH=$HOME/go && export GOROOT=/usr/local/go && export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
      - sh: ci_scripts/create-ip-aliases.sh
      - cmd: choco install make
      - go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.42.0
      - make dep
      - make install-deps-ui
    
    before_build:
      - cmd: set GO111MODULE=on
      - cmd: make check-windows-appveyor
      - sh: make check
      - make lint-ui
  
    build_script:
      - make build
      - make build-ui

  - # Linux (Release)
    skip_non_tags: true
    matrix:
      only:
        - job_name: linux-arm
        - job_name: linux-arm64
        - job_name: linux-amd64
        - job_name: linux-386

    install:
      - make dep
      - sh: ci_scripts/create-ip-aliases.sh
      - export GOARM=7
    
    build_script:
      - make build

    after_build:
      - sh: tar -cvzf skywire-$APPVEYOR_REPO_TAG_NAME-$APPVEYOR_JOB_NAME.tar.gz ./apps/* ./skywire-visor ./skywire-cli ./setup-node

    artifacts:
      - path: skywire-$(APPVEYOR_REPO_TAG_NAME)-$(APPVEYOR_JOB_NAME).tar.gz
        name: deploy

    deploy:
      - provider: GitHub
        release: $(APPVEYOR_REPO_TAG_NAME)
        auth_token:
          secure: ZrbNBE2wSfGvHzEq5GqEAUmNy7myDIl7KK05CKlZdQfieV7XdIAPXpkdHNEyZbvT
        draft: true
        artifact: deploy
        on:
          APPVEYOR_REPO_TAG: true
          
  - # Windows and MacOS (Release)
    skip_non_tags: true
    matrix:
      only:
        - job_name: darwin-amd64
        - job_name: windows-amd64

    environment:
      matrix:
        - GOARCH: amd64

    install:
      - sh: curl -OL "https://golang.org/dl/go1.16.6.darwin-amd64.tar.gz" && sudo tar -C /usr/local -xzf go1.16.6.darwin-amd64.tar.gz && export GOPATH=$HOME/go && export GOROOT=/usr/local/go && export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
      - sh: ci_scripts/create-ip-aliases.sh
      - cmd: choco install make
      - make dep
  
    build_script:
      - make build

    after_build:
      - sh: tar -cvzf skywire-$APPVEYOR_REPO_TAG_NAME-$APPVEYOR_JOB_NAME.tar.gz ./apps/* ./skywire-visor ./skywire-cli ./setup-node

    artifacts:
      - path: skywire-$(APPVEYOR_REPO_TAG_NAME)-$(APPVEYOR_JOB_NAME).tar.gz
        name: deploy
        
    deploy:
      - provider: GitHub
        release: $(APPVEYOR_REPO_TAG_NAME)
        auth_token:
          secure: ZrbNBE2wSfGvHzEq5GqEAUmNy7myDIl7KK05CKlZdQfieV7XdIAPXpkdHNEyZbvT
        draft: true
        artifact: deploy
        on:
          APPVEYOR_REPO_TAG: true
